var routes = [
{"route_id":1365,"agency_id":14,"route_short_name":3,"route_long_name":"Maplewood &harr; Hospital","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1367,"agency_id":14,"route_short_name":4,"route_long_name":"Hospital &harr; Maplewood","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1351,"agency_id":14,"route_short_name":14,"route_long_name":"Cordata/WCC &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1353,"agency_id":14,"route_short_name":"14S","route_long_name":"Shuttle","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1354,"agency_id":14,"route_short_name":15,"route_long_name":"Downtown &harr; Cordata/WCC","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1361,"agency_id":14,"route_short_name":24,"route_long_name":"Tremont &harr; Cordata/WCC","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1362,"agency_id":14,"route_short_name":"25X","route_long_name":"Lynden &harr; Bellingham/WWU","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1363,"agency_id":14,"route_short_name":26,"route_long_name":"Lynden &harr; Cordata/WCC","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1364,"agency_id":14,"route_short_name":27,"route_long_name":"Ferndale &harr; Cordata/WCC","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1369,"agency_id":14,"route_short_name":43,"route_long_name":"Yew St. AM &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1370,"agency_id":14,"route_short_name":44,"route_long_name":"Yew St. PM &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1371,"agency_id":14,"route_short_name":48,"route_long_name":"Bakerview Spur &harr; Cordata/WCC","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1372,"agency_id":14,"route_short_name":49,"route_long_name":"Bakerview Spur &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1373,"agency_id":14,"route_short_name":50,"route_long_name":"Gooseberry Pt. &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1377,"agency_id":14,"route_short_name":55,"route_long_name":"Cordata/WCC &harr; Blaine/Birch Bay","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1378,"agency_id":14,"route_short_name":"70X","route_long_name":"Blaine &harr; Bellingham/WWU","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1379,"agency_id":14,"route_short_name":"71X","route_long_name":"Everson/Nooksack/Sumas &harr; B'ham","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1380,"agency_id":14,"route_short_name":"72X","route_long_name":"Kendall &harr; Bellingham","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1383,"agency_id":14,"route_short_name":"80S","route_long_name":"Shuttle","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1384,"agency_id":14,"route_short_name":"80X","route_long_name":"Mt. Vernon &harr; Bellingham","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1385,"agency_id":14,"route_short_name":"90A","route_long_name":"WWU &harr; Lincoln Creek","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1387,"agency_id":14,"route_short_name":"90B","route_long_name":"WWU &harr; Lincoln Creek","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1344,"agency_id":14,"route_short_name":105,"route_long_name":"Fairhaven &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1346,"agency_id":14,"route_short_name":"105S","route_long_name":"Shuttle","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1347,"agency_id":14,"route_short_name":107,"route_long_name":"WWU &harr; Samish/Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1348,"agency_id":14,"route_short_name":108,"route_long_name":"Samish/WWU &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1350,"agency_id":14,"route_short_name":"108S","route_long_name":"Shuttle","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1355,"agency_id":14,"route_short_name":190,"route_long_name":"Lincoln Creek &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1357,"agency_id":14,"route_short_name":196,"route_long_name":"WWU/Lincoln &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1359,"agency_id":14,"route_short_name":197,"route_long_name":"Lincoln/WWU &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1360,"agency_id":14,"route_short_name":232,"route_long_name":"Cordata/WCC &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1366,"agency_id":14,"route_short_name":331,"route_long_name":"Cordata/WCC &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1368,"agency_id":14,"route_short_name":401,"route_long_name":"Fairhaven &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1374,"agency_id":14,"route_short_name":512,"route_long_name":"Sudden Valley &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1375,"agency_id":14,"route_short_name":525,"route_long_name":"Sunset &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""},
{"route_id":1376,"agency_id":14,"route_short_name":540,"route_long_name":"Squalicum H.S. &harr; Downtown","route_desc":"","route_type":3,"route_url":"","route_color":"","route_text_color":""}
]